# shrink_ppt
:author: Mischa Soujon
:email: mischa@soujon-net.de
:date: 2020-11-15T10:12:42.564Z
:toc:

Short bash script to shrink the images inside a PowerPoint presentation (nearly) without loss of quality.

## PITFALLS
The script is a quick-and-dirty implementation and everything else than production ready!

Please use it onw you own risk and be sure to have a backup of you original presentation.

## Prerequisites

The main resizing is based on functions of link:https://imagemagick.org[ImageMagick] and some math you need to install:

- link:https://imagemagick.org/script/download.php[ImageMagick - Download]
- GNU Basic Calculator **bc** (see: link:https://man7.org/linux/man-pages/man1/bc.1p.html[bc man page])

If you have LibreOffice installed, also EMF/WMF images will be resized. Make sure the ```soffice``` is in your path. On a Mac OS normally you will find the application in ```/Applications/LibreOffice.app/Contents/MacOS/```.

## Operation

The script take the first argument as PowerPoint presentation in pptx format to shrink.

It creates the folders:

extraction:: This folder contains the unzip presentation
img:: The images (jpeg, png, gif) to shrink which are found by search in ``extraction/ppt/media``` on files greater than 250 kilobyte
emf:: The embeded images (Windows Embeded Metafiles, emf) to shrink which are found by search in ``extraction/ppt/media``` on files greater than 250 kilobyte
resized:: The resized images

Normal images will be resized with imagemagick and if possible (no opacity) converted to JPEG images. The emf-files will be first converted to OpenOffice documents and then the PNG images extracted. If such an image is greater in size then 250k it will be resized and converted as above described.

After resizing the references in the presentation are updated and the shrunk presentation will be zip as ```shrunk_```_<OriginalPresentationName>_.pptx
